// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package models

import (
	
)

type UsersUser struct {
	UserEntityID int32          `db:"user_entity_id" json:"userEntityId"`
	UserName     string `db:"user_name" json:"userName"`
	UserEmail    string `db:"user_email" json:"userEmail"`
	UserGender   string `db:"user_gender" json:"userGender"`
}
